import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  BasicUsageSidebar: [
    {
      type: "autogenerated",
      dirName: "Basic Usage",
    },
  ],
  CustomizationSidebar: [
    {
      type: "autogenerated",
      dirName: "Customization",
    },
  ],
  IntegrationsSidebar: [
    {
      type: "autogenerated",
      dirName: "Integrations",
    },
  ],
  ResourceHubSidebar: [
    {
      type: "autogenerated",
      dirName: "Resource Hub",
    },
  ],
  HelpSidebar: [
    {
      type: "autogenerated",
      dirName: "Help",
    },
  ],
};

export default sidebars;
