import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  QuickstartSidebar: [
    {
      type: "autogenerated",
      dirName: "Quickstart", // the rest will be autogenerated
      
    },
  ],
  BasicUsageSidebar: [
    {
      type: "autogenerated",
      dirName: "Basic Usage",
    },
  ],
  CustomizationSidebar: [
    {
      type: "autogenerated",
      dirName: "Customization",
    },
  ],
  IntegrationsSidebar: [
    {
      type: "autogenerated",
      dirName: "Integrations",
    },
  ],
};

export default sidebars;
